### ISSUE TITLE
The number of cases in the provided BCSS

### ISSUE THREAD

**Issue by zhi-xuan-chen** [cvlab-stonybrook/SAMPath#12]
Hello! The original BCSS has 20,000 patches, but why does your provided processed BCSS only have about 3,000 samples?

**Comment by jingweizhang-xyz** [comment]
From the official website: "The BCSS dataset contains over 20,000 segmentation ANNOTATIONS of tissue region from breast cancer images from TCGA." One sample usually contains multiple annotations.

**Comment by zhi-xuan-chen** [comment]
OK, I get it! Thanks!

发件人: Jingwei Zhang ***@***.***>
日期: 星期三, 2024年8月21日 00:27
收件人: cvlab-stonybrook/SAMPath ***@***.***>
抄送: CHEN Zhixuan ***@***.***>, Author ***@***.***>
主题: Re: [cvlab-stonybrook/SAMPath] The number of cases in the provided BCSS (Issue #12)

From the official website: "The BCSS dataset contains over 20,000 segmentation ANNOTATIONS of tissue region from breast cancer images from TCGA." One sample usually contains multiple annotations.

―
