### ISSUE TITLE
The preprocess of the dataset

### ISSUE THREAD

**Issue by zhi-xuan-chen** [cvlab-stonybrook/SAMPath#14]

**Comment by zhi-xuan-chen** [comment]
I want to ask how you preprocess the BCSS and CRAG dataset from the raw dataset?

**Comment by jingweizhang-xyz** [comment]
For the GlaS dataset, we mainly convert its instance labels to the semantic labels. 
For the BCSS dataset, we split patches of each file in the dataset as the input resolution of SAM is 1024x1024. Also, we use only tumour, stroma, inflammatory, necrosis and other classes in the dataset.

**Comment by zhi-xuan-chen** [comment]
How you split them into patches? For example, the overlap between different patches.

**Comment by jingweizhang-xyz** [comment]
#3
