### ISSUE TITLE
The difference between ignored_classes and ignored_classes_metric in the config file

### ISSUE THREAD

**Issue by zhi-xuan-chen** [cvlab-stonybrook/SAMPath#16]
I noticed there two ignore class in the config, what is the difference of them?

**Comment by jingweizhang-xyz** [comment]
1. We do not calculate loss nor metrics for unlabeled region. ("ignored_classes")
2. We calculate loss for background region but do not include it when calculating metrics. ("ignored_classes_metric")

**Comment by zhi-xuan-chen** [comment]
OK, so if the background loss does not be counted into training, will it affect the performance?

**Comment by jingweizhang-xyz** [comment]
In that case the network will make a easy decision: predict very pixel to be gland because there will be no penalty on that.

**Comment by zhi-xuan-chen** [comment]
Right, thank you!
