### ISSUE TITLE
Would you offer a pre-trained model?

### ISSUE THREAD

**Issue by li-li-github** [cvlab-stonybrook/SAMPath#2]
Hi, 
I was going to try this model but couldn't find a pre-trained model.
The code seems to try to load a checkpoint from  `"/data07/shared/jzhang/result/weights/SAM/sam_vit_b_01ec64.pth"` but I can't find it in the repo. 
Will you be able to provide a pre-trained model for me to try your work?

Thank you!

**Comment by jingweizhang-xyz** [comment]
Oh, that's the original SAM model, you can find the original model from the official SAM repository: https://github.com/facebookresearch/segment-anything under "Model Checkpoints", the vit_b model can be downloaded from: https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth

**Comment by li-li-github** [comment]
Yeah, I also figured that out when I was surfing the original SAM repo. Thanks for your prompt reply! 
I guess for the DINO checkpoint("/data07/shared/jzhang/result/weights/HIPT/vit256_small_dino.pth"), I'd need to pull it from this [repo](https://github.com/mahmoodlab/HIPT#pre-reqs--installation)?

**Comment by jingweizhang-xyz** [comment]
Yes, you are right.

**Comment by li-li-github** [comment]
Thanks! It'd be nice if you could post the links to the readme to help people find them.
