### ISSUE TITLE
two class

### ISSUE THREAD

**Issue by 06Liz** [cvlab-stonybrook/SAMPath#20]
How can I use my dataset to train a model of one class?

**Comment by jingweizhang-xyz** [comment]
Just like what we do with the CRAG dataset, treat all other pixels as background. You can also check #15 and #16 for more details on how we process them.

**Comment by 06Liz** [comment]
My dataset has only one class.What should I do preprocess?

**Comment by jingweizhang-xyz** [comment]
Crop/resize them into 1024x1024 patches and label background as 0, your class as 1. Follow the CRAG configs.
