### ISSUE TITLE
Question about the number of classes for the BCSS dataset.

### ISSUE THREAD

**Issue by windygoo** [cvlab-stonybrook/SAMPath#6]
In the config file, I see the number of classes for the BCSS dataset is set to 6. However, shouldn't the number of categories be 5: Tumor, Stroma, Inflammatory, Necrosis and Others?

**Comment by jingweizhang-xyz** [comment]
The BCSS dataset contains some unlabeled regions. Unlike the 5 classes, they should not be included in metrics calculation. We use class 0 to represent this case and ignore it in the metrics calculation (Line 35 in main.py).

**Comment by windygoo** [comment]
> The BCSS dataset contains some unlabeled regions. Unlike the 5 classes, they should not be included in metrics calculation. We use class 0 to represent this case and ignore it in the metrics calculation (Line 35 in main.py).

I see. But since the class number has been increased by 1 in the config file, why it is increased further by 1 in the code? (Line 32 in main.py) and (Line 161 in network/sam_network.py)

**Comment by jingweizhang-xyz** [comment]
I can not remember clearly. That's probably because of a background class for calculating losses. The CRAG dataset contains a class background which should be included in loss calculation but not in metrics calculation. 
You can have a try to remove the +1 to see if there will be a problem. Even if there is an extra class, I think it would not affect the performance.

**Comment by windygoo** [comment]
> I can not remember clearly. That's probably because of a background class for calculating losses. The CRAG dataset contains a class background which should be included in loss calculation but not in metrics calculation. You can have a try to remove the +1 to see if there will be a problem. Even if there is an extra class, I think it would not affect the performance.

Thanks !
