### ISSUE TITLE
Some problems about SAMPath

### ISSUE THREAD

**Issue by NanCheng2001** [cvlab-stonybrook/SAMPath#8]
Thank you for your outstanding work！

I would like to ask, what are the equipment requirements for your model training, and at least how much GPUmemory is required? Because your article does not specify which parameters are frozen and which parameters need to be retuned.

**Comment by jingweizhang-xyz** [comment]
I did not remember the exact numbers. I think it should be <10GB for given batch size. The network is very light-weighted. Because the feature backbone is frozen and the rests are fine tuned but they do not have many parameters.

**Comment by NanCheng2001** [comment]
Thank you for your patience.
